### ISSUE TITLE
Settings not applied at Windows 10 Home 1709

### ISSUE THREAD

**Issue by db71** [Fleex255/PolicyPlus#4]
I tried gpedit on Windows 10 Home 1709 and Policy Plus, but none of the settings are actually applied. Some people say that an security update ('MS16-072: Security update for Group Policy') blocked the Policies in Windows 10 Home and some say that you need a Pro or Enterprice licence...

**Comment by Fleex255** [comment]
Thanks for the report! How did you install `gpedit`? I realized that one method of getting the Local Group Policy Editor on Home editions installs a file that causes Policy Plus to think it's on a Pro edition. If that happens, Policy Plus won't emulate the policy Registry applier and the settings won't work. I will get this fixed soon. If that isn't the problem in your case, though, we'll have a bit more investigating to do.

**Comment by db71** [comment]
I used the bat file on this website:

https://www.itechtics.com/easily-enable-group-policy-editor-gpedit-msc-in-windows-10-home-edition/

In the comment section there is a comments which could be the issue with later Windows 10 builds:

> Most GPO policies in W10 are now restricted by Product Policy Licenses so adding the GPO or equivalent registry value to unsupported Edition will have no effect. So even if you are installing Group Policy Editor, the policies will not work until you get a license for Windows 10 Pro or Enterprise editions.

From the event viewer when changing one setting in gpedit:

'Service configuration update to standalone is not required and will be skipped.'

No events when using Policy Plus

**Comment by Fleex255** [comment]
Ah yes, that is the script that partially installs Group Policy on Home editions. I say "partially" because it extracts a bunch of policy-related files (which [makes Policy Plus think](https://github.com/Fleex255/PolicyPlus/blob/master/PolicyPlus/PolicyLoader.vb#L125) Windows can handle the Registry application phase), but doesn't actually cause Windows to do the job. I'm finding it difficult to programmatically tell apart Home-with-inert-LGPE and Pro editions, but you can work around the issue by renaming or removing `secpol.msc`. Then Policy Plus will do the Registry editing itself, with the caveat that it will assume previously-set policy settings were successfully applied from before, so the differencer won't set them. You can fix *that* by moving or removing the contents of `C:\Windows\System32\GroupPolicy`, then making your changes afresh.

Sorry for the confusion. Hopefully I can figure out how to distinguish truly GP-enabled editions, then this won't be an issue. Most of the policy settings should work; it's just the script-installed LGPE that doesn't correctly apply the Administrative Templates settings.

**Comment by db71** [comment]
Thanks. It's working well now. Renaming the secpol.msc did the trick. I needed to take ownership for it, but Policy Plus works fine now.

One more question. Can I change a different non-admin users GPO when I'm logged in as administrator?

**Comment by Fleex255** [comment]
Yes, you can use *File | Open Policy Resources*, then in the user section, select the "user hive" corresponding to the user whose policies you want to edit.

**Comment by db71** [comment]
Great. I like this application better than gpedit and the mmc...

**Comment by Fleex255** [comment]
The underlying problem (the inability to detect whether the current computer actually has functional Group Policy infrastructure) should now be fixed in https://github.com/Fleex255/PolicyPlus/commit/3d46eed5700dcc015270568a4b2fd23914888d51.

**Comment by jjasoncool** [comment]
> Ah yes, that is the script that partially installs Group Policy on Home editions. I say "partially" because it extracts a bunch of policy-related files (which [makes Policy Plus think](https://github.com/Fleex255/PolicyPlus/blob/master/PolicyPlus/PolicyLoader.vb#L125) Windows can handle the Registry application phase), but doesn't actually cause Windows to do the job. I'm finding it difficult to programmatically tell apart Home-with-inert-LGPE and Pro editions, but you can work around the issue by renaming or removing `secpol.msc`. Then Policy Plus will do the Registry editing itself, with the caveat that it will assume previously-set policy settings were successfully applied from before, so the differencer won't set them. You can fix _that_ by moving or removing the contents of `C:\Windows\System32\GroupPolicy`, then making your changes afresh.
> 
> Sorry for the confusion. Hopefully I can figure out how to distinguish truly GP-enabled editions, then this won't be an issue. Most of the policy settings should work; it's just the script-installed LGPE that doesn't correctly apply the Administrative Templates settings.

I follow the step in quote comments, but in window 10 1803 setting still doesn't work.
I have rename secpol.msc and remove `C:\Windows\System32\GroupPolicy` and restart the computer.
It's doesn't work and window update still install any time.

**Comment by Fleex255** [comment]
@jjasoncool Windows has gotten increasingly enthusiastic about automatically installing updates. Can you make sure that the "configure automatic updating" dropdown is set to "3 - Auto download and notify for install" and that the "No auto-restart with logged on users for scheduled automatic updates installations" policy is Enabled?

**Comment by jjasoncool** [comment]
I have not set "No auto-restart with logged on users for scheduled automatic updates installations" policy is Enabled.

In my experience, I thought that as long as the "configure automatic updating" drop-down is set to "3 - Auto download and notify for install" is well done.

I will observe for a while.
Thank you!

**Comment by jjasoncool** [comment]
Hello,
I have follow the setting as you say.
Today window still update and restart.
have any advice?

**Comment by Fleex255** [comment]
@jjasoncool Sorry for the late reply. Let's have a look at the Registry; it's possible that it got out of sync with the Registry sometime before you followed the steps you quoted. Please have a look at this key:

    HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU

There should be entries named `AUOptions` and `NoAutoRebootWithLoggedOnUsers`, among others. Do you have those?

**Comment by jjasoncool** [comment]
![image](https://user-images.githubusercontent.com/24731867/50125675-da304780-02a4-11e9-88e1-bcee6f9ae81a.png)
No, I'm use window home but doesn't have `WindowsUpdate\AU`

**Comment by Fleex255** [comment]
OK, that indicates that the Registry was never synchronized with the POL files, probably due to the now-fixed bug. To get them back in sync, first set the update-related entries to Not Configured. Use *File | Save Policies* to remove those records from the POL file. Then set the policies back to what you want and use *File | Save Policies* again to put them back into the POL file and into the Registry.

**Comment by jjasoncool** [comment]
Sorry, what is "POL files"?

**Comment by jjasoncool** [comment]
![image](https://user-images.githubusercontent.com/24731867/52618172-051bce00-2ed9-11e9-8b21-f43bb3b485ad.png)

After few weeks, window update still working in the computer.
The version is 1803.
I have do the setting upon steps.
anything should I do?

**Comment by guzelonur** [comment]
I have Windows 10 **Home** 21H1 and many Group Policy registry settings like ExcludeWUDriversInQualityUpdate are not applied and they are simply ignored by Windows 10. Are many GPO settings now unsupported on Home editions? Does someone have a real info on this?
